tasks:
  file_path: Tasks.xlsx
  sheet_name: Sprint1
sprint:
  start_of_sprint: 1643401800  # start of the sprint (Unix epoch time to avoid timezone problems)
  day_time: 7.5  # Hours to be spent in each working day
  sprint_days: [1,1,1,1,1,1,0,1,1,1,1,1,1,0]  # One for working days - Zero for off days
clockify:
  api_key: <API KEY>  # Find it in https://clockify.me/user/settings
  workspace_name: ''  # name of the workspace in clockify (leave it blank if you have just one workspace)
  user_name: ''  # Leave it blank if you are the only user
